--- 
---
apiVersion: v1
data: 
  run.sh: |
      #!/bin/bash
      cd /usr/src
      git --version
      basedir=$(echo $gitrepo | sed 's/\// /g' | awk '{ print $NF}' | sed 's/.git//')
      #################### 
      #echo checking if workspace needs to be removed
      if [ "$cleanworkspace" = true ] ; then
      #echo "deleting workspace $basedir"
      rm -rf $basedir
      fi
      ####################  
      echo checking if $basedir exists
      if [ -d "$basedir" ]; then
      echo updating "$basedir"
      cd $basedir
      else
      echo cloning "$basedir"
      git clone  -b "$gitbranch" "https://"$gitusername":"$gitpassword"@"$gitrepo""
      
      cd $basedir
      fi
      #########################
      git status
      echo
      echo current revision of workspace is 
      git rev-parse HEAD
      revision=$(git rev-parse HEAD) 
      echo
      echo Outputs: 
      echo
      echo SPINNAKER_PROPERTY_COMMITID="$revision"
      echo
      echo running maven
      cd /usr/src/"$pomxmlpath"
      ./gradlew clean build
kind: ConfigMap
metadata: 
  name: issugen-gradle-script
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newgitrepo-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
---
apiVersion: v1
data:
  gitpassword: USERNAME
  gitusername: PASSWORD
kind: Secret
metadata:
  name: gitsecret

