---
apiVersion: v1
kind: Service
metadata:
  name: tech-talk
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    lb: tech-talk
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: tech-talk
  name: tech-talk
  namespace: dev
spec:
  rules:
    - http:
        paths:
          - backend:
            serviceName: tech-talk
            servicePort: http
          path: /dev/tech-talk