apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-talk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-talk
  template:
    metadata:
      labels:
        app: tech-talk
        lb: tech-talk
    spec:
      containers:
        - image: 'justinrlee/nginx:${parameters["tag"]}'
          name: primary
          ports:
            - containerPort: 80